/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/UESTC-KEEP/keep/cloud/pkg/apis/keepedge/tenantresourcequota/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// TenantResourceQuotaLister helps list TenantResourceQuotas.
// All objects returned here must be treated as read-only.
type TenantResourceQuotaLister interface {
	// List lists all TenantResourceQuotas in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.TenantResourceQuota, err error)
	// TenantResourceQuotas returns an object that can list and get TenantResourceQuotas.
	TenantResourceQuotas(namespace string) TenantResourceQuotaNamespaceLister
	TenantResourceQuotaListerExpansion
}

// tenantResourceQuotaLister implements the TenantResourceQuotaLister interface.
type tenantResourceQuotaLister struct {
	indexer cache.Indexer
}

// NewTenantResourceQuotaLister returns a new TenantResourceQuotaLister.
func NewTenantResourceQuotaLister(indexer cache.Indexer) TenantResourceQuotaLister {
	return &tenantResourceQuotaLister{indexer: indexer}
}

// List lists all TenantResourceQuotas in the indexer.
func (s *tenantResourceQuotaLister) List(selector labels.Selector) (ret []*v1alpha1.TenantResourceQuota, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.TenantResourceQuota))
	})
	return ret, err
}

// TenantResourceQuotas returns an object that can list and get TenantResourceQuotas.
func (s *tenantResourceQuotaLister) TenantResourceQuotas(namespace string) TenantResourceQuotaNamespaceLister {
	return tenantResourceQuotaNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// TenantResourceQuotaNamespaceLister helps list and get TenantResourceQuotas.
// All objects returned here must be treated as read-only.
type TenantResourceQuotaNamespaceLister interface {
	// List lists all TenantResourceQuotas in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.TenantResourceQuota, err error)
	// Get retrieves the TenantResourceQuota from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.TenantResourceQuota, error)
	TenantResourceQuotaNamespaceListerExpansion
}

// tenantResourceQuotaNamespaceLister implements the TenantResourceQuotaNamespaceLister
// interface.
type tenantResourceQuotaNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all TenantResourceQuotas in the indexer for a given namespace.
func (s tenantResourceQuotaNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.TenantResourceQuota, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.TenantResourceQuota))
	})
	return ret, err
}

// Get retrieves the TenantResourceQuota from the indexer for a given namespace and name.
func (s tenantResourceQuotaNamespaceLister) Get(name string) (*v1alpha1.TenantResourceQuota, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("tenantresourcequota"), name)
	}
	return obj.(*v1alpha1.TenantResourceQuota), nil
}
