/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	versioned "keep/cloud/pkg/client/clientset/versioned"
	internalinterfaces "keep/cloud/pkg/client/informers/externalversions/internalinterfaces"
	v1 "keep/cloud/pkg/client/listers/keepcrd/v1"
	keepcrdv1 "keep/cloud/pkg/k8sclient/crd_engin/keepcrd/pkg/apis/keepedge/v1"
	time "time"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// EqualNodeInformer provides access to a shared informer and lister for
// EqualNodes.
type EqualNodeInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.EqualNodeLister
}

type equalNodeInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewEqualNodeInformer constructs a new informer for EqualNode type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewEqualNodeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredEqualNodeInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredEqualNodeInformer constructs a new informer for EqualNode type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredEqualNodeInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KeepedgeV1().EqualNodes(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.KeepedgeV1().EqualNodes(namespace).Watch(context.TODO(), options)
			},
		},
		&keepcrdv1.EqualNode{},
		resyncPeriod,
		indexers,
	)
}

func (f *equalNodeInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredEqualNodeInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *equalNodeInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&keepcrdv1.EqualNode{}, f.defaultInformer)
}

func (f *equalNodeInformer) Lister() v1.EqualNodeLister {
	return v1.NewEqualNodeLister(f.Informer().GetIndexer())
}
